### ISSUE TITLE
ValueError raised in lightkurve.correctors.DesignMatrix.pca for some targets

### ISSUE THREAD

**Issue by icweaver** [christinahedges/TESS-SIP#6]
Hi @christinahedges, thanks for such a cool package! The example code in the README works great, but when I try it for a couple other targets. For example,

```python
import lightkurve as lk
from tess_sip import SIP

tpfs = lk.search_targetpixelfile("WASP-50").download_all()
r = SIP(tpfs)
```
I get the following error:

```
/home/mango/miniconda3/envs/gen/lib/python3.9/site-packages/lightkurve/lightcurve.py:1031: LightkurveWarning: The light curve appears to be zero-centered (median=1.94e+04 electron / s +/- 5.24e+04 electron / s); `normalize()` will divide the light curve by a value close to zero, which is probably not what you want.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-541ad68d42d6> in <module>
----> 1 r = SIP(tpfs)

~/Projects/TESS-SIP/src/tess_sip/tess_sip.py in SIP(tpfs, sigma, min_period, max_period, nperiods, npca_components, aperture_threshold, sff, sff_kwargs)
    145     with warnings.catch_warnings():
    146         warnings.simplefilter("ignore")
--> 147         bkgs = [
    148             lk.correctors.DesignMatrix(tpf.flux.value[:, bkg_aper], name="bkg")
    149             .pca(npca_components)

~/Projects/TESS-SIP/src/tess_sip/tess_sip.py in <listcomp>(.0)
    146         warnings.simplefilter("ignore")
    147         bkgs = [
--> 148             lk.correctors.DesignMatrix(tpf.flux.value[:, bkg_aper], name="bkg")
    149             .pca(npca_components)
    150             .append_constant()

~/miniconda3/envs/gen/lib/python3.9/site-packages/lightkurve/correctors/designmatrix.py in pca(self, nterms)
    275         from fbpca import pca  # local import because not used elsewhere
    276 
--> 277         new_values, _, _ = pca(self.values, nterms, n_iter=10)
    278         return DesignMatrix(new_values, name=self.name)
    279 

~/miniconda3/envs/gen/lib/python3.9/site-packages/fbpca.py in pca(A, k, raw, n_iter, l)
   1670                 (Q, _) = qr(Q, mode='economic')
   1671             if n_iter > 0:
-> 1672                 (Q, _) = lu(Q, permute_l=True)
   1673 
   1674             #

~/miniconda3/envs/gen/lib/python3.9/site-packages/scipy/linalg/decomp_lu.py in lu(a, permute_l, overwrite_a, check_finite)
    207     """
    208     if check_finite:
--> 209         a1 = asarray_chkfinite(a)
    210     else:
    211         a1 = asarray(a)

~/miniconda3/envs/gen/lib/python3.9/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
    486     a = asarray(a, dtype=dtype, order=order)
    487     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
--> 488         raise ValueError(
    489             "array must not contain infs or NaNs")
    490     return a

ValueError: array must not contain infs or NaNs
```

Trying with another target, like WASP-96b for example, raises the same zero-centered warning, but then seems to run as expected, so I do not know if this could be related to the value error that seems to be raised in `lk.correctors.DesignMatrix.pca`

Trying the fix suggested [here](https://github.com/lightkurve/lightkurve/issues/569#issuecomment-534346264) for the initial warning at least does not seem to change things, I think because the [|median_flux| is still < 0.5*std_flux](https://github.com/barentsen/lightkurve/blob/5b1693832bc509e42742d1b6f20224d131e62d8c/lightkurve/lightcurve.py#L734) in the background pixels in my particular case

**Comment by christinahedges** [comment]
Hi @icweaver,

I think there are two problems here, first there is a bug in the `TESS-SIP` code which will try to PCA nan values (not possible), and the second is that the lightkurve API has changed. When you're downloading tpfs in that line, you're actually going to get the same TPF multiple times from different "authors" (e.g. TESS-SPOC, MIT etc). This will break TESS-SIP, because it'll try to fit the same dataset twice. You can specify an author by e.g. doing

```python
lk.search_targetpixelfile("WASP-50", author='SPOC')
```

I've pushed changes that fix the issue with TESS-SIP, which is caused when there are nan values in the time series. Give it a try now, and let me know if you still find the same issue! Make sure to update your version.

Thanks for the comment and the great MWE!!

**Comment by icweaver** [comment]
Woohoo, works like a charm! Thanks for the tip about the authors, I will be sure to double check my downloaded products from now on =]
